# Using the read mapping summary generated by Genboree, this code extracts the percentage of reads mapped to a specific annotated element
# Author Candida Vaz
#!/usr/bin/perl
use strict;
use warnings;

my$file=$ARGV[0];
open(IN,"$file");
my@arr=<IN>;
chomp(@arr);
my$len=@arr;


my@header=(); my@ele=(); my$l=0;

(my$name,my$ext)=split(/\./,$file);
(my$ext1,my$fin)=split("-23-Sept-",$name);
open (OUT,">$fin-percent.txt");

@header = split(/\t/,$arr[0]);
print "$header[0]\t$header[1]\n";

for(my$i=1;$i<$len;$i++)
  {
    @ele=split(/\t/,$arr[$i]);
    my$l=@ele;
    my@per=();
    print OUT ("$ele[0]\n");#ele[0] is the sample name
    for(my$j=2;$j<$l;$j++)
      {
        $per[$j] = ($ele[$j]/$ele[1]) * 100;#ele[1] is the total number of reads in that sample
        print OUT ("$header[$j]\t$ele[$j]\t$per[$j]\n");
      }
       print OUT ("********************\n");
  }

close (IN);
close (OUT);
